In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("students.csv")

In [3]:
df

    Name   Age  Marks
0   Arun  21.0   85.0
1   Bala  22.0   72.0
2  Kumar  20.0   91.0
3  Divya  21.0    8.0
4      8   NaN    NaN
5   Ravi  23.0   67.0

In [4]:
df.head()

    Name   Age  Marks
0   Arun  21.0   85.0
1   Bala  22.0   72.0
2  Kumar  20.0   91.0
3  Divya  21.0    8.0
4      8   NaN    NaN

In [5]:
df.head()

    Name   Age  Marks
0   Arun  21.0   85.0
1   Bala  22.0   72.0
2  Kumar  20.0   91.0
3  Divya  21.0    8.0
4      8   NaN    NaN

In [6]:
df.tail()

    Name   Age  Marks
1   Bala  22.0   72.0
2  Kumar  20.0   91.0
3  Divya  21.0    8.0
4      8   NaN    NaN
5   Ravi  23.0   67.0

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      str
 1   Age     5 non-null      float64
 2   Marks   5 non-null      float64
dtypes: float64(2), str(1)
memory usage: 276.0 bytes

In [8]:
df.describe()

             Age      Marks
count   5.000000   5.000000
mean   21.400000  64.600000
std     1.140175  33.080206
min    20.000000   8.000000
25%    21.000000  67.000000
50%    21.000000  72.000000
75%    22.000000  85.000000
max    23.000000  91.000000

# Day 10 - Student Data Inspection

## Dataset Overview

This notebook loads and inspects the student dataset.

### Inspection steps
- Load the CSV file
- View the first and last rows
- Check columns and data types
- Check missing values
- View numerical statistics